/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 * Partline - Mock Data & Realistic Automotive Dataset
 */

import {
  PartlinePart,
  PartlineOrganization,
  WorkOrder,
  StockMovement,
  ActivityEvent,
  PurchaseOrder,
} from '../../types/partline';

export const INITIAL_ORGANIZATIONS: PartlineOrganization[] = [
  {
    id: 'org-almansour-01',
    name: 'Al-Mansour Automotive Group',
    slug: 'al-mansour-auto',
    plan: 'enterprise',
    primaryCity: 'Baghdad',
  },
  {
    id: 'org-erbil-logistics-02',
    name: 'Erbil Central Logistics Depot',
    slug: 'erbil-logistics',
    plan: 'growth',
    primaryCity: 'Erbil',
  },
  {
    id: 'org-basra-marine-03',
    name: 'Basra Freight & Terminal Ops',
    slug: 'basra-marine',
    plan: 'growth',
    primaryCity: 'Basra',
  },
];

export const INITIAL_PARTS: PartlinePart[] = [
  {
    id: 'part-prado-rotors-01',
    orgId: 'org-almansour-01',
    sku: 'BRK-TOY-43512-PRD',
    name: 'Front Vented Brake Disc Rotors (Pair)',
    slug: 'front-vented-brake-disc-rotors-pair',
    brand: 'Advics Japan OEM',
    categoryId: 'cat-brakes',
    categoryName: 'Brake System',
    oemNumber: '43512-60191',
    condition: 'oem',
    status: 'active',
    unit: 'pair',
    costCents: 9200, // $92.00
    priceCents: 14500, // $145.00
    currency: 'USD',
    weightG: 17500,
    dimsMm: [338, 338, 70],
    attrs: {
      rotorDiameterMm: 338,
      thicknessMm: 32,
      boltPattern: '6x139.7',
      heatTreated: true,
      antiCorrosionCoating: 'Geomet Zinc-Flake',
    },
    imageUrl: 'https://images.unsplash.com/photo-1600790142055-619df03207e6?auto=format&fit=crop&w=600&q=80',
    totalQtyOnHand: 48,
    totalQtyReserved: 6,
    totalQtyIncoming: 24,
    isLowStock: false,
    createdAt: '2026-03-10T08:00:00Z',
    updatedAt: '2026-09-18T14:20:00Z',
    fitments: [
      {
        id: 'fit-prado-01',
        partId: 'part-prado-rotors-01',
        vehicleMake: 'Toyota',
        vehicleModel: 'Land Cruiser Prado',
        generation: 'J150 Facelift',
        yearRange: '2018 - 2024',
        engineCode: '1GR-FE 4.0L V6 Dual VVT-i',
        displacementL: 4.0,
        position: 'front',
        qty: 2,
        confidence: 0.99, // Guaranteed fit
        verifiedAt: '2026-08-12T10:30:00Z',
        source: 'catalog',
      },
      {
        id: 'fit-prado-02',
        partId: 'part-prado-rotors-01',
        vehicleMake: 'Lexus',
        vehicleModel: 'GX460',
        generation: 'URJ150',
        yearRange: '2014 - 2023',
        engineCode: '1UR-FE 4.6L V8',
        displacementL: 4.6,
        position: 'front',
        qty: 2,
        confidence: 0.94, // Guaranteed fit
        verifiedAt: '2026-08-14T11:00:00Z',
        source: 'catalog',
      },
      {
        id: 'fit-prado-03',
        partId: 'part-prado-rotors-01',
        vehicleMake: 'Toyota',
        vehicleModel: '4Runner',
        generation: 'N280 TRD Off-Road',
        yearRange: '2020 - 2024',
        engineCode: '1GR-FE 4.0L V6',
        displacementL: 4.0,
        position: 'front',
        qty: 2,
        confidence: 0.81, // Below 0.85 -> Human review needed!
        verifiedAt: '2026-09-02T16:15:00Z',
        source: 'vision',
      },
    ],
    stockLevels: [
      {
        warehouseId: 'wh-bgd-01',
        warehouseCode: 'BGD-CENTRAL',
        warehouseName: 'Baghdad Distribution Hub',
        city: 'Baghdad',
        qtyOnHand: 28,
        qtyReserved: 4,
        qtyIncoming: 12,
        reorderPoint: 15,
        bin: 'A-12-04',
        updatedAt: '2026-09-19T09:00:00Z',
      },
      {
        warehouseId: 'wh-erbil-02',
        warehouseCode: 'ERB-DEPOT',
        warehouseName: 'Erbil North Logistics Hub',
        city: 'Erbil',
        qtyOnHand: 14,
        qtyReserved: 2,
        qtyIncoming: 12,
        reorderPoint: 10,
        bin: 'E-04-18',
        updatedAt: '2026-09-18T14:20:00Z',
      },
      {
        warehouseId: 'wh-basra-03',
        warehouseCode: 'BSR-TERM',
        warehouseName: 'Basra Marine Logistics Terminal',
        city: 'Basra',
        qtyOnHand: 6,
        qtyReserved: 0,
        qtyIncoming: 0,
        reorderPoint: 8,
        bin: 'B-02-09',
        updatedAt: '2026-09-15T11:45:00Z',
      },
    ],
  },
  {
    id: 'part-denso-injector-02',
    orgId: 'org-almansour-01',
    sku: 'INJ-DEN-23670-G6',
    name: 'Common Rail Diesel Injector (G3S G6)',
    slug: 'common-rail-diesel-injector-g3s-g6',
    brand: 'Denso Japan',
    categoryId: 'cat-fuel',
    categoryName: 'Fuel & Emission',
    oemNumber: '23670-0L090',
    condition: 'oem',
    status: 'active',
    unit: 'pc',
    costCents: 16500, // $165.00
    priceCents: 24500, // $245.00
    currency: 'USD',
    weightG: 680,
    dimsMm: [195, 45, 45],
    attrs: {
      pressureBar: 2000,
      injectionStages: 5,
      solenoidResistanceOhms: 0.35,
      calibrationCodePreProgrammed: true,
    },
    imageUrl: 'https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?auto=format&fit=crop&w=600&q=80',
    totalQtyOnHand: 12,
    totalQtyReserved: 2,
    totalQtyIncoming: 18,
    isLowStock: true, // Low stock alert!
    createdAt: '2026-02-14T09:00:00Z',
    updatedAt: '2026-09-20T10:15:00Z',
    fitments: [
      {
        id: 'fit-hilux-01',
        partId: 'part-denso-injector-02',
        vehicleMake: 'Toyota',
        vehicleModel: 'Hilux Revo / Rocco',
        generation: 'AN120',
        yearRange: '2016 - 2024',
        engineCode: '1GD-FTV 2.8L D-4D',
        displacementL: 2.8,
        position: 'none',
        qty: 4,
        confidence: 0.98,
        verifiedAt: '2026-07-20T08:00:00Z',
        source: 'catalog',
      },
      {
        id: 'fit-fortuner-02',
        partId: 'part-denso-injector-02',
        vehicleMake: 'Toyota',
        vehicleModel: 'Fortuner',
        generation: 'AN160',
        yearRange: '2017 - 2024',
        engineCode: '1GD-FTV 2.8L D-4D',
        displacementL: 2.8,
        position: 'none',
        qty: 4,
        confidence: 0.97,
        verifiedAt: '2026-07-22T14:30:00Z',
        source: 'catalog',
      },
    ],
    stockLevels: [
      {
        warehouseId: 'wh-bgd-01',
        warehouseCode: 'BGD-CENTRAL',
        warehouseName: 'Baghdad Distribution Hub',
        city: 'Baghdad',
        qtyOnHand: 4,
        qtyReserved: 2,
        qtyIncoming: 12,
        reorderPoint: 12,
        bin: 'B-09-02',
        updatedAt: '2026-09-20T10:15:00Z',
      },
      {
        warehouseId: 'wh-erbil-02',
        warehouseCode: 'ERB-DEPOT',
        warehouseName: 'Erbil North Logistics Hub',
        city: 'Erbil',
        qtyOnHand: 8,
        qtyReserved: 0,
        qtyIncoming: 6,
        reorderPoint: 8,
        bin: 'E-01-11',
        updatedAt: '2026-09-19T16:20:00Z',
      },
      {
        warehouseId: 'wh-basra-03',
        warehouseCode: 'BSR-TERM',
        warehouseName: 'Basra Marine Logistics Terminal',
        city: 'Basra',
        qtyOnHand: 0,
        qtyReserved: 0,
        qtyIncoming: 0,
        reorderPoint: 4,
        bin: 'B-01-01',
        updatedAt: '2026-09-10T12:00:00Z',
      },
    ],
  },
  {
    id: 'part-patrol-rack-03',
    orgId: 'org-almansour-01',
    sku: 'STR-NIS-49001-Y62',
    name: 'Electric Power Steering Rack & Pinion Assembly',
    slug: 'electric-power-steering-rack-pinion-assembly',
    brand: 'Hitachi Astemo OEM',
    categoryId: 'cat-steering',
    categoryName: 'Steering & Suspension',
    oemNumber: '49001-1LA0A',
    condition: 'oem',
    status: 'active',
    unit: 'pc',
    costCents: 68000, // $680.00
    priceCents: 98000, // $980.00
    currency: 'USD',
    weightG: 14200,
    dimsMm: [1120, 260, 180],
    attrs: {
      rackType: 'Dual-Pinion Electric Assist (EPS)',
      motorVolts: 12,
      turnsLockToLock: 3.1,
      tieRodsIncluded: true,
      sensorCalibrated: true,
    },
    imageUrl: 'https://images.unsplash.com/photo-1580273916550-e323be2ae537?auto=format&fit=crop&w=600&q=80',
    totalQtyOnHand: 5,
    totalQtyReserved: 1,
    totalQtyIncoming: 4,
    isLowStock: true,
    createdAt: '2026-04-01T10:00:00Z',
    updatedAt: '2026-09-19T18:00:00Z',
    fitments: [
      {
        id: 'fit-patrol-01',
        partId: 'part-patrol-rack-03',
        vehicleMake: 'Nissan',
        vehicleModel: 'Patrol Titanium / Platinum',
        generation: 'Y62 Facelift II',
        yearRange: '2020 - 2025',
        engineCode: 'VK56VD 5.6L V8 DIG',
        displacementL: 5.6,
        position: 'front',
        qty: 1,
        confidence: 0.99,
        verifiedAt: '2026-08-01T12:00:00Z',
        source: 'catalog',
      },
      {
        id: 'fit-qx80-02',
        partId: 'part-patrol-rack-03',
        vehicleMake: 'Infiniti',
        vehicleModel: 'QX80 ProActive',
        generation: 'Z62',
        yearRange: '2018 - 2023',
        engineCode: 'VK56VD 5.6L V8',
        displacementL: 5.6,
        position: 'front',
        qty: 1,
        confidence: 0.96,
        verifiedAt: '2026-08-05T14:10:00Z',
        source: 'catalog',
      },
    ],
    stockLevels: [
      {
        warehouseId: 'wh-bgd-01',
        warehouseCode: 'BGD-CENTRAL',
        warehouseName: 'Baghdad Distribution Hub',
        city: 'Baghdad',
        qtyOnHand: 3,
        qtyReserved: 1,
        qtyIncoming: 2,
        reorderPoint: 4,
        bin: 'RACK-03-B',
        updatedAt: '2026-09-19T18:00:00Z',
      },
      {
        warehouseId: 'wh-erbil-02',
        warehouseCode: 'ERB-DEPOT',
        warehouseName: 'Erbil North Logistics Hub',
        city: 'Erbil',
        qtyOnHand: 2,
        qtyReserved: 0,
        qtyIncoming: 2,
        reorderPoint: 3,
        bin: 'RACK-01-A',
        updatedAt: '2026-09-16T15:20:00Z',
      },
      {
        warehouseId: 'wh-basra-03',
        warehouseCode: 'BSR-TERM',
        warehouseName: 'Basra Marine Logistics Terminal',
        city: 'Basra',
        qtyOnHand: 0,
        qtyReserved: 0,
        qtyIncoming: 0,
        reorderPoint: 2,
        bin: 'RACK-01-C',
        updatedAt: '2026-09-10T12:00:00Z',
      },
    ],
  },
  {
    id: 'part-bmw-housing-04',
    orgId: 'org-almansour-01',
    sku: 'ENG-BMW-11428-B58',
    name: 'Engine Oil Filter Housing & Heat Exchanger Assembly',
    slug: 'engine-oil-filter-housing-heat-exchanger-assembly',
    brand: 'Mahle Motorsport / OE',
    categoryId: 'cat-cooling',
    categoryName: 'Cooling & Lubrication',
    oemNumber: '11428583895',
    condition: 'aftermarket',
    status: 'active',
    unit: 'kit',
    costCents: 11000,
    priceCents: 18500,
    currency: 'USD',
    weightG: 1850,
    dimsMm: [260, 210, 140],
    attrs: {
      housingMaterial: 'Upgraded Die-Cast Aluminum (Anti-Crack)',
      coolerPlates: 16,
      sealMaterial: 'Viton FKM Synthetic High-Temp',
      warrantyMonths: 24,
    },
    imageUrl: 'https://images.unsplash.com/photo-1619642751034-765dfdf7c58e?auto=format&fit=crop&w=600&q=80',
    totalQtyOnHand: 32,
    totalQtyReserved: 4,
    totalQtyIncoming: 15,
    isLowStock: false,
    createdAt: '2026-05-12T11:00:00Z',
    updatedAt: '2026-09-17T11:30:00Z',
    fitments: [
      {
        id: 'fit-bmw-340-01',
        partId: 'part-bmw-housing-04',
        vehicleMake: 'BMW',
        vehicleModel: '3 Series M340i / 440i',
        generation: 'G20 / G22',
        yearRange: '2019 - 2024',
        engineCode: 'B58B30O1 3.0L Turbo',
        displacementL: 3.0,
        position: 'none',
        qty: 1,
        confidence: 0.99,
        verifiedAt: '2026-08-10T10:00:00Z',
        source: 'catalog',
      },
      {
        id: 'fit-bmw-x5-02',
        partId: 'part-bmw-housing-04',
        vehicleMake: 'BMW',
        vehicleModel: 'X5 xDrive40i',
        generation: 'G05',
        yearRange: '2019 - 2024',
        engineCode: 'B58B30M1 3.0L Turbo',
        displacementL: 3.0,
        position: 'none',
        qty: 1,
        confidence: 0.98,
        verifiedAt: '2026-08-12T15:20:00Z',
        source: 'catalog',
      },
      {
        id: 'fit-supra-03',
        partId: 'part-bmw-housing-04',
        vehicleMake: 'Toyota',
        vehicleModel: 'GR Supra 3.0',
        generation: 'A90 / DB42',
        yearRange: '2020 - 2024',
        engineCode: 'B58B30 3.0L Turbo',
        displacementL: 3.0,
        position: 'none',
        qty: 1,
        confidence: 0.95,
        verifiedAt: '2026-08-15T09:40:00Z',
        source: 'manual',
      },
    ],
    stockLevels: [
      {
        warehouseId: 'wh-bgd-01',
        warehouseCode: 'BGD-CENTRAL',
        warehouseName: 'Baghdad Distribution Hub',
        city: 'Baghdad',
        qtyOnHand: 18,
        qtyReserved: 3,
        qtyIncoming: 10,
        reorderPoint: 8,
        bin: 'C-04-12',
        updatedAt: '2026-09-17T11:30:00Z',
      },
      {
        warehouseId: 'wh-erbil-02',
        warehouseCode: 'ERB-DEPOT',
        warehouseName: 'Erbil North Logistics Hub',
        city: 'Erbil',
        qtyOnHand: 10,
        qtyReserved: 1,
        qtyIncoming: 5,
        reorderPoint: 6,
        bin: 'E-08-04',
        updatedAt: '2026-09-16T14:10:00Z',
      },
      {
        warehouseId: 'wh-basra-03',
        warehouseCode: 'BSR-TERM',
        warehouseName: 'Basra Marine Logistics Terminal',
        city: 'Basra',
        qtyOnHand: 4,
        qtyReserved: 0,
        qtyIncoming: 0,
        reorderPoint: 4,
        bin: 'B-03-08',
        updatedAt: '2026-09-12T10:00:00Z',
      },
    ],
  },
  {
    id: 'part-mercedes-alt-05',
    orgId: 'org-almansour-01',
    sku: 'ELC-MB-00090-ISG',
    name: 'Integrated 48V Starter-Alternator Assembly (EQ Boost)',
    slug: 'integrated-48v-starter-alternator-assembly-eq-boost',
    brand: 'Bosch Automotive OEM',
    categoryId: 'cat-electrical',
    categoryName: 'Electrical & Ignition',
    oemNumber: 'A0009068804',
    condition: 'oem_surplus',
    status: 'active',
    unit: 'pc',
    costCents: 52000,
    priceCents: 74000,
    currency: 'USD',
    weightG: 9800,
    dimsMm: [280, 240, 220],
    attrs: {
      voltage: '48V Mild-Hybrid',
      powerKW: 16,
      maxTorqueNm: 250,
      liquidCooled: true,
      beltlessDesign: true,
    },
    imageUrl: 'https://images.unsplash.com/photo-1542282088-72c9c27ed0cd?auto=format&fit=crop&w=600&q=80',
    totalQtyOnHand: 8,
    totalQtyReserved: 2,
    totalQtyIncoming: 6,
    isLowStock: false,
    createdAt: '2026-06-05T09:00:00Z',
    updatedAt: '2026-09-18T10:15:00Z',
    fitments: [
      {
        id: 'fit-mb-c200-01',
        partId: 'part-mercedes-alt-05',
        vehicleMake: 'Mercedes-Benz',
        vehicleModel: 'C-Class C200 / C300',
        generation: 'W206',
        yearRange: '2021 - 2025',
        engineCode: 'M254 2.0L Turbo 48V',
        displacementL: 2.0,
        position: 'none',
        qty: 1,
        confidence: 0.98,
        verifiedAt: '2026-08-20T11:00:00Z',
        source: 'catalog',
      },
      {
        id: 'fit-mb-e300-02',
        partId: 'part-mercedes-alt-05',
        vehicleMake: 'Mercedes-Benz',
        vehicleModel: 'E-Class E350 / E450',
        generation: 'W213 Facelift',
        yearRange: '2021 - 2024',
        engineCode: 'M256 3.0L Inline-6 48V',
        displacementL: 3.0,
        position: 'none',
        qty: 1,
        confidence: 0.82, // Below 0.85 -> Human review needed!
        verifiedAt: '2026-09-01T15:00:00Z',
        source: 'vision',
      },
    ],
    stockLevels: [
      {
        warehouseId: 'wh-bgd-01',
        warehouseCode: 'BGD-CENTRAL',
        warehouseName: 'Baghdad Distribution Hub',
        city: 'Baghdad',
        qtyOnHand: 5,
        qtyReserved: 1,
        qtyIncoming: 4,
        reorderPoint: 4,
        bin: 'E-SEC-01',
        updatedAt: '2026-09-18T10:15:00Z',
      },
      {
        warehouseId: 'wh-erbil-02',
        warehouseCode: 'ERB-DEPOT',
        warehouseName: 'Erbil North Logistics Hub',
        city: 'Erbil',
        qtyOnHand: 3,
        qtyReserved: 1,
        qtyIncoming: 2,
        reorderPoint: 2,
        bin: 'E-SEC-03',
        updatedAt: '2026-09-15T12:00:00Z',
      },
      {
        warehouseId: 'wh-basra-03',
        warehouseCode: 'BSR-TERM',
        warehouseName: 'Basra Marine Logistics Terminal',
        city: 'Basra',
        qtyOnHand: 0,
        qtyReserved: 0,
        qtyIncoming: 0,
        reorderPoint: 2,
        bin: 'B-SEC-01',
        updatedAt: '2026-09-10T12:00:00Z',
      },
    ],
  },
  {
    id: 'part-tucson-compressor-06',
    orgId: 'org-almansour-01',
    sku: 'AC-HYU-97701-NX4',
    name: 'Dual-Zone Variable Displacement A/C Compressor',
    slug: 'dual-zone-variable-displacement-ac-compressor',
    brand: 'Hanon Systems Korea',
    categoryId: 'cat-cooling',
    categoryName: 'Cooling & Lubrication',
    oemNumber: '97701-N9000',
    condition: 'oem',
    status: 'active',
    unit: 'pc',
    costCents: 18500,
    priceCents: 27500,
    currency: 'USD',
    weightG: 5800,
    dimsMm: [210, 160, 160],
    attrs: {
      refrigerant: 'R134a / R1234yf compatible',
      pulleyRibs: 6,
      displacementCC: 160,
      oilType: 'PAG 46 Factory Filled 150ml',
    },
    imageUrl: 'https://images.unsplash.com/photo-1517524008697-84bbe3c3fd98?auto=format&fit=crop&w=600&q=80',
    totalQtyOnHand: 22,
    totalQtyReserved: 3,
    totalQtyIncoming: 12,
    isLowStock: false,
    createdAt: '2026-05-18T14:00:00Z',
    updatedAt: '2026-09-19T13:40:00Z',
    fitments: [
      {
        id: 'fit-tucson-01',
        partId: 'part-tucson-compressor-06',
        vehicleMake: 'Hyundai',
        vehicleModel: 'Tucson SmartStream',
        generation: 'NX4',
        yearRange: '2021 - 2025',
        engineCode: 'G4FP 1.6L T-GDI',
        displacementL: 1.6,
        position: 'none',
        qty: 1,
        confidence: 0.99,
        verifiedAt: '2026-07-28T09:00:00Z',
        source: 'catalog',
      },
      {
        id: 'fit-sportage-02',
        partId: 'part-tucson-compressor-06',
        vehicleMake: 'Kia',
        vehicleModel: 'Sportage GT-Line',
        generation: 'NQ5',
        yearRange: '2022 - 2025',
        engineCode: 'G4FP 1.6L T-GDI',
        displacementL: 1.6,
        position: 'none',
        qty: 1,
        confidence: 0.98,
        verifiedAt: '2026-07-30T10:30:00Z',
        source: 'catalog',
      },
    ],
    stockLevels: [
      {
        warehouseId: 'wh-bgd-01',
        warehouseCode: 'BGD-CENTRAL',
        warehouseName: 'Baghdad Distribution Hub',
        city: 'Baghdad',
        qtyOnHand: 12,
        qtyReserved: 2,
        qtyIncoming: 8,
        reorderPoint: 8,
        bin: 'C-08-01',
        updatedAt: '2026-09-19T13:40:00Z',
      },
      {
        warehouseId: 'wh-erbil-02',
        warehouseCode: 'ERB-DEPOT',
        warehouseName: 'Erbil North Logistics Hub',
        city: 'Erbil',
        qtyOnHand: 7,
        qtyReserved: 1,
        qtyIncoming: 4,
        reorderPoint: 6,
        bin: 'E-03-09',
        updatedAt: '2026-09-17T16:00:00Z',
      },
      {
        warehouseId: 'wh-basra-03',
        warehouseCode: 'BSR-TERM',
        warehouseName: 'Basra Marine Logistics Terminal',
        city: 'Basra',
        qtyOnHand: 3,
        qtyReserved: 0,
        qtyIncoming: 0,
        reorderPoint: 4,
        bin: 'B-04-03',
        updatedAt: '2026-09-14T09:00:00Z',
      },
    ],
  },
  {
    id: 'part-hilux-timing-07',
    orgId: 'org-almansour-01',
    sku: 'ENG-TOY-13568-KIT',
    name: 'Complete Heavy Duty Timing Chain Kit w/ Tensioners',
    slug: 'complete-heavy-duty-timing-chain-kit-w-tensioners',
    brand: 'Toyota Genuine Parts',
    categoryId: 'cat-engine',
    categoryName: 'Engine Core',
    oemNumber: '13568-39016',
    condition: 'oem',
    status: 'active',
    unit: 'kit',
    costCents: 12500,
    priceCents: 19500,
    currency: 'USD',
    weightG: 4200,
    dimsMm: [340, 240, 90],
    attrs: {
      chainsIncluded: 2,
      hydraulicTensioners: 2,
      guidesSprockets: 4,
      nitrideHardened: true,
    },
    imageUrl: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=600&q=80',
    totalQtyOnHand: 36,
    totalQtyReserved: 5,
    totalQtyIncoming: 20,
    isLowStock: false,
    createdAt: '2026-02-10T12:00:00Z',
    updatedAt: '2026-09-20T09:10:00Z',
    fitments: [
      {
        id: 'fit-hilux-2tr-01',
        partId: 'part-hilux-timing-07',
        vehicleMake: 'Toyota',
        vehicleModel: 'Hilux Single/Double Cab',
        generation: 'AN120 / AN130',
        yearRange: '2015 - 2024',
        engineCode: '2TR-FE 2.7L Petrol Dual VVT-i',
        displacementL: 2.7,
        position: 'none',
        qty: 1,
        confidence: 1.0,
        verifiedAt: '2026-07-15T08:00:00Z',
        source: 'catalog',
      },
      {
        id: 'fit-fortuner-2tr-02',
        partId: 'part-hilux-timing-07',
        vehicleMake: 'Toyota',
        vehicleModel: 'Fortuner 4x2 / 4x4',
        generation: 'AN160',
        yearRange: '2016 - 2024',
        engineCode: '2TR-FE 2.7L Petrol',
        displacementL: 2.7,
        position: 'none',
        qty: 1,
        confidence: 1.0,
        verifiedAt: '2026-07-16T11:00:00Z',
        source: 'catalog',
      },
    ],
    stockLevels: [
      {
        warehouseId: 'wh-bgd-01',
        warehouseCode: 'BGD-CENTRAL',
        warehouseName: 'Baghdad Distribution Hub',
        city: 'Baghdad',
        qtyOnHand: 20,
        qtyReserved: 3,
        qtyIncoming: 12,
        reorderPoint: 10,
        bin: 'K-02-10',
        updatedAt: '2026-09-20T09:10:00Z',
      },
      {
        warehouseId: 'wh-erbil-02',
        warehouseCode: 'ERB-DEPOT',
        warehouseName: 'Erbil North Logistics Hub',
        city: 'Erbil',
        qtyOnHand: 11,
        qtyReserved: 2,
        qtyIncoming: 8,
        reorderPoint: 8,
        bin: 'E-05-14',
        updatedAt: '2026-09-18T10:00:00Z',
      },
      {
        warehouseId: 'wh-basra-03',
        warehouseCode: 'BSR-TERM',
        warehouseName: 'Basra Marine Logistics Terminal',
        city: 'Basra',
        qtyOnHand: 5,
        qtyReserved: 0,
        qtyIncoming: 0,
        reorderPoint: 4,
        bin: 'B-02-04',
        updatedAt: '2026-09-15T16:00:00Z',
      },
    ],
  },
  {
    id: 'part-landcruiser-strut-08',
    orgId: 'org-almansour-01',
    sku: 'SUS-TOY-48510-LC3',
    name: 'Front Adaptive Variable Suspension Shock Absorber (AVS)',
    slug: 'front-adaptive-variable-suspension-shock-absorber-avs',
    brand: 'Tokico / Hitachi OE',
    categoryId: 'cat-steering',
    categoryName: 'Steering & Suspension',
    oemNumber: '48510-60290',
    condition: 'oem',
    status: 'active',
    unit: 'pc',
    costCents: 21000,
    priceCents: 32000,
    currency: 'USD',
    weightG: 6400,
    dimsMm: [610, 140, 140],
    attrs: {
      type: 'Electronically Controlled Damping Monotube',
      gasPressureBar: 25,
      pistonRodMm: 22,
      strokeMm: 185,
    },
    imageUrl: 'https://images.unsplash.com/photo-1563720223185-11003d516935?auto=format&fit=crop&w=600&q=80',
    totalQtyOnHand: 14,
    totalQtyReserved: 2,
    totalQtyIncoming: 10,
    isLowStock: false,
    createdAt: '2026-06-10T10:00:00Z',
    updatedAt: '2026-09-19T17:15:00Z',
    fitments: [
      {
        id: 'fit-lc300-01',
        partId: 'part-landcruiser-strut-08',
        vehicleMake: 'Toyota',
        vehicleModel: 'Land Cruiser 300 ZX / GR-Sport',
        generation: 'LC300',
        yearRange: '2022 - 2025',
        engineCode: 'V35A-FTS 3.5L Twin-Turbo V6',
        displacementL: 3.5,
        position: 'front_left',
        qty: 1,
        confidence: 0.99,
        verifiedAt: '2026-08-01T14:00:00Z',
        source: 'catalog',
      },
      {
        id: 'fit-lx600-02',
        partId: 'part-landcruiser-strut-08',
        vehicleMake: 'Lexus',
        vehicleModel: 'LX600 VIP / F-Sport',
        generation: 'VJA310',
        yearRange: '2022 - 2025',
        engineCode: 'V35A-FTS 3.5L Twin-Turbo V6',
        displacementL: 3.5,
        position: 'front_left',
        qty: 1,
        confidence: 0.97,
        verifiedAt: '2026-08-03T16:20:00Z',
        source: 'catalog',
      },
    ],
    stockLevels: [
      {
        warehouseId: 'wh-bgd-01',
        warehouseCode: 'BGD-CENTRAL',
        warehouseName: 'Baghdad Distribution Hub',
        city: 'Baghdad',
        qtyOnHand: 8,
        qtyReserved: 1,
        qtyIncoming: 6,
        reorderPoint: 6,
        bin: 'S-01-04',
        updatedAt: '2026-09-19T17:15:00Z',
      },
      {
        warehouseId: 'wh-erbil-02',
        warehouseCode: 'ERB-DEPOT',
        warehouseName: 'Erbil North Logistics Hub',
        city: 'Erbil',
        qtyOnHand: 4,
        qtyReserved: 1,
        qtyIncoming: 4,
        reorderPoint: 4,
        bin: 'E-02-12',
        updatedAt: '2026-09-18T11:40:00Z',
      },
      {
        warehouseId: 'wh-basra-03',
        warehouseCode: 'BSR-TERM',
        warehouseName: 'Basra Marine Logistics Terminal',
        city: 'Basra',
        qtyOnHand: 2,
        qtyReserved: 0,
        qtyIncoming: 0,
        reorderPoint: 2,
        bin: 'B-01-08',
        updatedAt: '2026-09-14T10:00:00Z',
      },
    ],
  },
];

export const INITIAL_WORK_ORDERS: WorkOrder[] = [
  {
    id: 'wo-01',
    code: 'WO-2026-0481',
    partId: 'part-prado-rotors-01',
    partName: 'Front Vented Brake Disc Rotors (Pair)',
    partSku: 'BRK-TOY-43512-PRD',
    qtyPlanned: 50,
    qtyProduced: 32,
    qtyScrapped: 1,
    status: 'in_progress',
    priority: 'high',
    dueAt: '2026-09-24T18:00:00Z',
    assigneeName: 'Ali Al-Hashimi (Senior CNC)',
    station: 'Station 3: Precision Balancing & Heat Treat',
    createdAt: '2026-09-18T08:30:00Z',
    steps: [
      { seq: 1, name: 'Billet Cast Quality Scan', station: 'Station 1: Raw Audit', status: 'passed', durationMinutes: 45, operatorName: 'Karrar M.' },
      { seq: 2, name: 'CNC Lathe Face & Vent Milling', station: 'Station 2: Machining', status: 'passed', durationMinutes: 120, operatorName: 'Ali Al-Hashimi' },
      { seq: 3, name: 'Precision Dynamic Balancing', station: 'Station 3: Balancing', status: 'active', durationMinutes: 60, operatorName: 'Ali Al-Hashimi' },
      { seq: 4, name: 'Zinc-Flake Anti-Corrosion Dip', station: 'Station 4: Coating', status: 'pending', durationMinutes: 90 },
      { seq: 5, name: 'Laser Etching & Final QC Gate', station: 'Station 5: Inspection', status: 'pending', durationMinutes: 30 },
    ],
  },
  {
    id: 'wo-02',
    code: 'WO-2026-0482',
    partId: 'part-denso-injector-02',
    partName: 'Common Rail Diesel Injector (G3S G6)',
    partSku: 'INJ-DEN-23670-G6',
    qtyPlanned: 30,
    qtyProduced: 30,
    qtyScrapped: 0,
    status: 'qc',
    priority: 'urgent',
    dueAt: '2026-09-21T12:00:00Z',
    assigneeName: 'Zaid Al-Bayati (Fuel Sys Tech)',
    station: 'Station 5: Hartridge High-Pressure Bench Calibration',
    createdAt: '2026-09-17T09:15:00Z',
    steps: [
      { seq: 1, name: 'Nozzle Micron Bore Inspection', station: 'Station 1: Optics', status: 'passed', durationMinutes: 30, operatorName: 'Zaid Al-Bayati' },
      { seq: 2, name: 'Piezo/Solenoid Actuator Torque', station: 'Station 2: Assembly', status: 'passed', durationMinutes: 90, operatorName: 'Zaid Al-Bayati' },
      { seq: 3, name: '2000 Bar Spray Pattern Test', station: 'Station 3: Pressure', status: 'passed', durationMinutes: 75, operatorName: 'Omar F.' },
      { seq: 4, name: 'IMA Flow Coding Calibration', station: 'Station 4: Software', status: 'active', durationMinutes: 45, operatorName: 'Zaid Al-Bayati' },
    ],
  },
  {
    id: 'wo-03',
    code: 'WO-2026-0479',
    partId: 'part-patrol-rack-03',
    partName: 'Electric Power Steering Rack & Pinion Assembly',
    partSku: 'STR-NIS-49001-Y62',
    qtyPlanned: 10,
    qtyProduced: 10,
    qtyScrapped: 0,
    status: 'completed',
    priority: 'normal',
    dueAt: '2026-09-19T17:00:00Z',
    assigneeName: 'Mustafa Tariq (EPS Specialist)',
    station: 'Station 6: Packaging & Dispatch',
    createdAt: '2026-09-15T07:00:00Z',
    steps: [
      { seq: 1, name: 'Gear Teeth Hardness Test', station: 'Station 1', status: 'passed', durationMinutes: 40 },
      { seq: 2, name: 'EPS Motor Torque Calibrate', station: 'Station 2', status: 'passed', durationMinutes: 80 },
      { seq: 3, name: 'Waterproof Seal Pressure Test', station: 'Station 3', status: 'passed', durationMinutes: 40 },
      { seq: 4, name: 'CAN-Bus Diagnostic Sync', station: 'Station 4', status: 'passed', durationMinutes: 30 },
    ],
  },
  {
    id: 'wo-04',
    code: 'WO-2026-0485',
    partId: 'part-bmw-housing-04',
    partName: 'Engine Oil Filter Housing & Heat Exchanger Assembly',
    partSku: 'ENG-BMW-11428-B58',
    qtyPlanned: 40,
    qtyProduced: 0,
    qtyScrapped: 0,
    status: 'released',
    priority: 'normal',
    dueAt: '2026-09-28T16:00:00Z',
    assigneeName: 'Hussein J. (BOM Tech)',
    station: 'Station 1: Die-Cast CNC Trimming',
    createdAt: '2026-09-20T08:00:00Z',
    steps: [
      { seq: 1, name: 'Die-Cast Ingot Milling', station: 'Station 1', status: 'pending', durationMinutes: 60 },
      { seq: 2, name: '16-Plate Cooler Brazing', station: 'Station 2', status: 'pending', durationMinutes: 90 },
      { seq: 3, name: 'Helium Leak Vacuum Gate', station: 'Station 3', status: 'pending', durationMinutes: 45 },
    ],
  },
];

export const INITIAL_STOCK_MOVEMENTS: StockMovement[] = [
  {
    id: 'mv-01',
    partId: 'part-prado-rotors-01',
    warehouseId: 'wh-bgd-01',
    warehouseName: 'Baghdad Distribution Hub',
    delta: 50,
    reason: 'receipt',
    refType: 'purchase_order',
    refId: 'PO-2026-0189',
    actorName: 'Haider Abbas (Warehouse Manager)',
    createdAt: '2026-09-18T11:20:00Z',
  },
  {
    id: 'mv-02',
    partId: 'part-prado-rotors-01',
    warehouseId: 'wh-bgd-01',
    warehouseName: 'Baghdad Distribution Hub',
    delta: -4,
    reason: 'sale',
    refType: 'dispatch_order',
    refId: 'ORD-9831',
    actorName: 'Platform Dispatch Auto-Route',
    createdAt: '2026-09-19T14:05:00Z',
  },
  {
    id: 'mv-03',
    partId: 'part-denso-injector-02',
    warehouseId: 'wh-bgd-01',
    warehouseName: 'Baghdad Distribution Hub',
    delta: -8,
    reason: 'transfer',
    refType: 'inter_warehouse_transfer',
    refId: 'XFER-BGD-ERB-04',
    actorName: 'Sarmad Kamil (Logistics Lead)',
    createdAt: '2026-09-20T09:30:00Z',
  },
  {
    id: 'mv-04',
    partId: 'part-patrol-rack-03',
    warehouseId: 'wh-bgd-01',
    warehouseName: 'Baghdad Distribution Hub',
    delta: -1,
    reason: 'sale',
    refType: 'dispatch_order',
    refId: 'ORD-9912',
    actorName: 'Platform Dispatch Auto-Route',
    createdAt: '2026-09-20T11:45:00Z',
  },
  {
    id: 'mv-05',
    partId: 'part-bmw-housing-04',
    warehouseId: 'wh-erbil-02',
    warehouseName: 'Erbil North Logistics Hub',
    delta: 15,
    reason: 'receipt',
    refType: 'purchase_order',
    refId: 'PO-2026-0194',
    actorName: 'Ramiar Botan (Erbil Inventory)',
    createdAt: '2026-09-17T15:10:00Z',
  },
];

export const INITIAL_ACTIVITY: ActivityEvent[] = [
  {
    id: 'act-01',
    type: 'wo_status',
    title: 'Work Order Advanced to QC',
    description: 'WO-2026-0482 (Denso Injectors x30) completed IMA calibration and moved to final quality gate.',
    timestamp: '14 minutes ago',
    actor: 'Zaid Al-Bayati',
    badgeColor: 'amber',
  },
  {
    id: 'act-02',
    type: 'audit_alert',
    title: 'Low Stock Threshold Triggered',
    description: 'Denso Common Rail Injectors in Baghdad Hub dropped to 4 units (Reorder Point: 12).',
    timestamp: '1 hour ago',
    actor: 'Automated Stock Engine',
    badgeColor: 'rose',
  },
  {
    id: 'act-03',
    type: 'fitment_verified',
    title: 'Guaranteed Fitment Approved',
    description: 'Tokico AVS Shock Absorber fitment for Toyota Land Cruiser 300 ZX confirmed with 99% confidence.',
    timestamp: '3 hours ago',
    actor: 'Dr. Tariq (Vehicle Catalog Lead)',
    badgeColor: 'emerald',
  },
  {
    id: 'act-04',
    type: 'stock_receipt',
    title: 'PO-2026-0189 Received & Shelved',
    description: '50 units of Advics Prado Brake Rotors received at Baghdad Hub Bay 4.',
    timestamp: 'Yesterday at 16:40',
    actor: 'Haider Abbas',
    badgeColor: 'indigo',
  },
];

export const INITIAL_PURCHASE_ORDERS: PurchaseOrder[] = [
  {
    id: 'po-01',
    code: 'PO-2026-0198',
    supplierId: 'sup-denso-uae',
    supplierName: 'Denso Middle East FZE (Jebel Ali)',
    status: 'sent',
    totalCents: 495000, // $4,950.00
    currency: 'USD',
    expectedAt: '2026-09-27T00:00:00Z',
    createdAt: '2026-09-19T10:00:00Z',
    lines: [
      {
        id: 'pol-01',
        partId: 'part-denso-injector-02',
        partSku: 'INJ-DEN-23670-G6',
        partName: 'Common Rail Diesel Injector (G3S G6)',
        qty: 30,
        receivedQty: 0,
        unitCostCents: 16500,
      },
    ],
  },
  {
    id: 'po-02',
    code: 'PO-2026-0195',
    supplierId: 'sup-advics-japan',
    supplierName: 'Advics Brake Systems Global Distribution',
    status: 'confirmed',
    totalCents: 920000,
    currency: 'USD',
    expectedAt: '2026-09-25T00:00:00Z',
    createdAt: '2026-09-18T14:00:00Z',
    lines: [
      {
        id: 'pol-02',
        partId: 'part-prado-rotors-01',
        partSku: 'BRK-TOY-43512-PRD',
        partName: 'Front Vented Brake Disc Rotors (Pair)',
        qty: 100,
        receivedQty: 50,
        unitCostCents: 9200,
      },
    ],
  },
];
